CREATE TABLE user(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  email VARCHAR(128) NOT NULL UNIQUE,
  password VARCHAR(128) NOT NULL,
  is_exist BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT current_timestamp
);

CREATE TABLE post(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  title VARCHAR(256) NOT NULL,
  content TEXT NOT NULL,
  author INTEGER NOT NULL references user(id),
  created_at TIMESTAMPTZ DEFAULT current_timestamp
);
